# Generated by Django 4.2.1 on 2024-05-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemetadata',
            name='id',
        ),
        migrations.AlterField(
            model_name='moviemetadata',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movie.movie'),
        ),
    ]
