# Generated by Django 5.1.1 on 2024-11-04 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_rating_movie_ratings"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", models.JSONField(blank=True, null=True)),
                (
                    "movie",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="movie.movie"),
                ),
            ],
        ),
    ]
