# Generated by Django 4.2.1 on 2024-05-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_moviemetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemetadata',
            name='Unnamed: 0',
        ),
    ]
