# Generated by Django 5.1.1 on 2024-11-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_actors_movieactor"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True,
                related_name="actors",
                through="movie.MovieActor",
                to="movie.actors",
            ),
        ),
    ]
