# Generated by Django 5.1.1 on 2024-11-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_movie_actors"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MovieEmbedding",
        ),
    ]
