# Generated by Django 5.1.1 on 2024-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0007_alter_movie_original_title_alter_movie_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actors",
            name="actor_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="movieactor",
            name="character_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="moviegenres",
            name="genre",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="movielanguages",
            name="language",
            field=models.CharField(max_length=512),
        ),
    ]
