# Generated by Django 5.1.1 on 2024-12-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0008_alter_actors_actor_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movie_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
