# Generated by Django 5.1.1 on 2025-01-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0010_usertopicdistribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicDescription",
            fields=[
                ("topic_id", models.IntegerField(primary_key=True, serialize=False)),
                ("top_words", models.JSONField()),
                ("label", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
