# Generated by Django 4.2.1 on 2024-06-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "movie",
                    models.ManyToManyField(related_name="playlist", to="movie.movie"),
                ),
            ],
        ),
    ]
