services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=movies.settings  # Replace with your actual settings module

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${db_user_name}
      POSTGRES_PASSWORD: ${db_psw}
      POSTGRES_DB: ${db_name}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
