services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=movies.settings
    command:
      - web

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery_worker
    depends_on:
      - web
      - redis
      - db
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=movies.settings



  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery_beat
    depends_on:
      - web
      - redis
      - db
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=movies.settings

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${db_user_name}
      POSTGRES_PASSWORD: ${db_psw}
      POSTGRES_DB: ${db_name}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
