version: '3.8'
services:
  web:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    volumes:
      - static_volume:/app/movies/collected_static/
    expose:
      - 8000
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=movies.settings.prod
      - DEBUG=False
    command: web

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - static_volume:/app/movies/collected_static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

  celery_worker:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    command: celery_worker
    depends_on:
      - web
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=movies.settings.prod
      - DEBUG=False

  celery_beat:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    command: celery_beat
    depends_on:
      - web
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=movies.settings.prod
      - DEBUG=False

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${db_user_name}
      POSTGRES_PASSWORD: ${db_psw}
      POSTGRES_DB: ${db_name}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  static_volume: