"""
Django settings for movies project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

print(BASE_DIR)

GENERAL = ["budget", "popularity", "year", "revenue", "runtime", "vote_average"]

GENRES = ['Foreign', 'Telescene Film Group Productions', 'Aniplex', 'Music', 'Comedy', 'Animation', 'Action', 'TV Movie', 'Sentai Filmworks',
        'Rogue State', 'Drama', 'Carousel Productions', 'Fantasy', 'Documentary',
        'Romance', 'Western', 'Odyssey Media', 'War', 'Vision View Entertainment', 'Mystery', 'The Cartel', 'Mardock Scramble Production Committee', 'Horror',
        'Thriller', 'GoHands', 'Family', 'Science Fiction', 'Adventure', 'Crime', 'History', 'BROSTA TV', 'Pulser Productions']

SPOKEN_LANGUAGES = ['Fulfulde',
                     'Czech',
                     'Bosnian',
                     'Norwegian',
                     'Latvian',
                     'French',
                     'Cantonese',
                     'Wolof',
                     'Pashto',
                     'Portuguese',
                     'Georgian',
                     'Punjabi',
                     'Malay',
                     'Azerbaijani',
                     'Slovak',
                     'Bambara',
                     'Afrikaans',
                     'Somali',
                     'Esperanto',
                     'Polish',
                     'English',
                     'Zulu',
                     'Arabic',
                     'Hebrew',
                     'Hindi',
                     'Catalan',
                     'Hausa',
                     'Italian',
                     'Slovenian',
                     'Albanian',
                     'Telugu',
                     'Swedish',
                     'Greek',
                     'Bengali',
                     'Estonian',
                     'Persian',
                     'Turkish',
                     'Romanian',
                     'Hungarian',
                     'Thai',
                     'Basque',
                     'Urdu',
                     'Icelandic',
                     'Japanese',
                     'Uzbek',
                     'Maltese',
                     'Vietnamese',
                     'German',
                     'Croatian',
                     'Russian',
                     'Serbian',
                     'Finnish',
                     'Kinyarwanda',
                     'Irish',
                     'Spanish',
                     'Lithuanian',
                     'Korean',
                     'Latin',
                     'Tamil',
                     'Bulgarian',
                     'Norwegian Bokmål',
                     'Swahili',
                     'Dutch',
                     'Danish',
                     'Galician',
                     'Welsh',
                     'Belarusian',
                     'Ukrainian',
                     'Mandarin',
                     'Kazakh',
                     'Indonesian']


FEATURES = GENERAL+GENRES+SPOKEN_LANGUAGES

METADATA_PATH = BASE_DIR / 'data' / 'movies_metadata_short.xlsx'
MODEL_DIR = BASE_DIR / 'word2vec.model'

#  metadata model reads the following file always


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f5^&ph#wvrn*=9k&t&422#0jc)1otk7+x6wnm%(&q!lien1g7y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

INTERNAL_IPS = ["127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'movie.apps.MovieConfig',
    'menu.apps.MenuConfig',
    'users.apps.UsersConfig',
    'playlist.apps.PlaylistConfig',
    'forum.apps.ForumConfig',
    "debug_toolbar",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'movies.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'movies.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": os.path.join(BASE_DIR, "movies_cache"),
        'TIMEOUT': 300,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'users:login'